### ISSUE TITLE
CORS wilcard origin not accepted

### ISSUE THREAD

**Issue by gulayciragiloglu79** [kocdigital/Carbon#45]
with carbon web application latest version(4.1.2) wilcard colud not  acceppted  even if  ı use http://*:*. 

config:
 "CorsPolicy": {
    "AllowAnyMethods": true,
    "AllowAnyHeaders": true,
    "AllowAnyOrigin": false,
    "AllowCredentials": true,
     "Origins": ["https://localhost:50001", "http://172.18.228.26:50080", "http://172.18.228.26:58085", "http://172.18.228.26:58585", "http://localhost:9528", "http://localhost:*", "http://*:*" ]
  },

**Comment by keremaytac** [comment]
Most probably related with the cors origin settings. To be fixed with Allowing wildcards in subdomains configuration.
